# Docker Compose for local development
version: '3.8'

services:
  spam-classifier:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
