# Railway deployment configuration
[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PYTHONPATH = "/app"
FLASK_ENV = "production"
